<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>LeanProd.Application</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>Enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\LeanProd.Domain\LeanProd.Domain.csproj" />
  </ItemGroup>
</Project>
